version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
    command: ["nohup", "jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''", "&" ]

